### ISSUE TITLE
[BUG]  node-gyp fsevent errors prevents building sample application using `skaffold dev` 

### ISSUE THREAD

**Issue by daxeh** [GoogleCloudPlatform/cloud-code-samples#315]
**Describe the bug**

Following tutorials and documentations referring to sample application however failed to progress due to build errors such as missing dependencies, incompatible node compiled code. ie.macOS host node engine compiled code is imcompatible with `node:10.15.3-alpine`

**To Reproduce**

1. clone repo `git@github.com:GoogleContainerTools/skaffold.git`
2. navigate to sample project `skaffold/examples/react-reload`
3. run command `skaffold dev`
4. error occurs in docker build `Step 6/7 : RUN npm ci`

**Expected behavior**

As a first sample application, I am excited to experience how I can benefit with `skaffold` to compliment learning and orchestration confidently using k8s integrated tools for a pleasant learning tutorial experience without daunting errors.

**Screenshots**
n/a

** Template in use:**
 - Path to template: skaffold/examples/react-reload/skaffold.yml

**Cloud Code in use:**
 - Cloud Code for VS Code, iterm2 3.3.9
 - OS: macOS darwin X86_64 Node v12.16.3 Docker version 19.03.8, VSCode 1.45.0 x64

**Additional context**

stdout output

```sh
> react-reload % /usr/local/bin/skaffold dev
Listing files to watch...
 - react-reload
Generating tags...
 - react-reload -> react-reload:v1.9.0-16-g58e72a691
Checking cache...
 - react-reload: Not found. Building
Building [react-reload]...
Sending build context to Docker daemon  303.6kB
Step 1/7 : FROM node:10.15.3-alpine
10.15.3-alpine: Pulling from library/node
e7c96db7181b: Pull complete
df9eac31dfef: Pull complete
0a20433d95a4: Pull complete
Digest: sha256:aa28f3b6b4087b3f289bebaca8d3fb82b93137ae739aa67df3a04892d521958e
Status: Downloaded newer image for node:10.15.3-alpine
 ---> 56bc3a1ed035
Step 2/7 : WORKDIR /app
 ---> Running in d8e7abf67a07
 ---> 73c22f4d9de5
Step 3/7 : EXPOSE 8080
 ---> Running in 4c36420ddfba
 ---> 473f3f888684
Step 4/7 : CMD ["npm", "run", "dev"]
 ---> Running in 62b4bb690803
 ---> 49e58c001b30
Step 5/7 : COPY package* ./
 ---> b7dcb8368775
Step 6/7 : RUN npm ci
 ---> Running in eac3ae24ee62

> fsevents@1.2.11 install /app/node_modules/fsevents
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Linux 4.19.76-linuxkit
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/fsevents
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
added 712 packages in 14.355s
 ---> fadd8f250347
Step 7/7 : COPY . .
 ---> ac57eedb5478
Successfully built ac57eedb5478
Successfully tagged react-reload:v1.9.0-16-g58e72a691
The push refers to repository [docker.io/library/react-reload]
8adbe8474f97: Preparing
5e6b1fd3307b: Preparing
7fafd33190fc: Preparing
54b49b4084a2: Preparing
28bf756b6f8e: Preparing
4c299e1e70d5: Waiting
f1b5933fe4b5: Waiting
exiting dev mode because first build failed: couldn't build "react-reload": denied: requested access to the resource is denied
```

**Comment by etanshaul** [comment]
@nkubala @balopat I think we should migrate this to the Skaffold repo. The application used is from the Skaffold examples.

**Comment by nkubala** [comment]
this isn't a bug - just an unhelpful error. in the logs i see 

`The push refers to repository [docker.io/library/react-reload]`

which you won't have access to, so your push will fail and skaffold will exit. the easiest way to get around this error would be to set your default repo to something you have access to:

`skaffold config set default-repo <my_image_repository>`

alternatively, if you use `minikube` or another local deployment tool, skaffold will skip pushing images altogether.
